# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees: [JosephKav]
    reviewers: [JosephKav]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees: [JosephKav]
    reviewers: [JosephKav]

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees: [JosephKav]
    reviewers: [JosephKav]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees: [JosephKav]
    reviewers: [JosephKav]
  - package-ecosystem: "npm"
    directory: "/web/ui/react-app/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees: [JosephKav]
    reviewers: [JosephKav]
