linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - depguard
    - dupl
    - dupword
    - durationcheck
    - errorlint
    - execinquery
    - gci
    - gocritic
    - misspell
    - typecheck
    - wrapcheck
    - errcheck
