name: Docker Build

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build-docker:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)"  >> ${GITHUB_ENV}
          echo "repository=${repository,,}" >> ${GITHUB_ENV}
          echo "repository_owner=${repository_owner,,}" >> ${GITHUB_ENV}
          echo "GO_VERSION=$(cat go.mod | grep -Po 'go \K([0-9.]+)')" >> ${GITHUB_ENV}
        env:
          repository: '${{ github.repository }}'
          repository_owner: '${{ github.repository_owner }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Login to Quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push (release)
        id: docker_build_release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            releaseargus/argus:${{ github.event.release.tag_name }}
            releaseargus/argus:latest
            ghcr.io/${{ env.repository }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ env.repository }}:latest
            quay.io/argus-io/argus:${{ github.event.release.tag_name }}
            quay.io/argus-io/argus:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm,linux/arm64
          provenance: false
          build-args: |
            BUILD_VERSION=${{ github.event.release.tag_name }}
            GO_VERSION=${{ env.GO_VERSION }}

      - name: Build and push (master)
        id: docker_build_master
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            releaseargus/argus:master
            ghcr.io/${{ env.repository }}:master
            quay.io/argus-io/argus:master
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm,linux/arm64
          provenance: false
          build-args: |
            BUILD_VERSION=${{ env.sha_short }}
            GO_VERSION=${{ env.GO_VERSION }}
