name: Codecov

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: go test -v ./... -coverpkg=./... -coverprofile ./coverage.out -covermode atomic --tags testing,unit,integration
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Publish coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true